# -*- coding: utf-8 -*-
"""Server Moniter Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10lflh1GiORzpSBl5c6NUTETuhczwpGoP
"""

import pandas as pd
from sqlalchemy import create_engine
import os

# Load CSV data
df = pd.read_csv("/content/Sample_Data_Ingestion.csv")

# Convert timestamp
df['Log_Timestamp'] = pd.to_datetime(df['Log_Timestamp'], format='%d-%m-%Y %H:%M')

# Remove duplicates
df = df.drop_duplicates()

# Create new metrics
df['Total_Network_Traffic'] = df['Network_Traffic_In (MB/s)'] + df['Network_Traffic_Out (MB/s)']

df['Availability'] = df['Uptime (Hours)'] / (df['Uptime (Hours)'] + df['Downtime (Hours)'])

df['High_CPU_Alert'] = df['CPU_Utilization (%)'] > 80

# Create database folder
os.makedirs("database", exist_ok=True)

# Save to database
db_engine = create_engine("sqlite:///database/server_monitoring.db")

df.to_sql("server_logs", db_engine, if_exists="replace", index=False)

print("Data pipeline executed successfully")

# Save cleaned data to CSV
df.to_csv("cleaned_server_data.csv", index=False)

# Save to SQLite database
db_engine = create_engine("sqlite:///database/server_monitoring.db")

df.to_sql(
    name="server_logs",
    con=db_engine,
    if_exists="replace",
    index=False
)

print("Data pipeline executed successfully")